import {ClassicAssets,Terrain} from './classic-assets.js';

const $=id=>document.getElementById(id),canvas=$('levelCanvas'),ctx=canvas.getContext('2d');
const names=['Klimmer','Zwever','Bomber','Blokkeren','Bouwer','Basher','Mijnwerker','Graver'];
const assets=new ClassicAssets();let data=null,records=[],selectedTool='terrain',selectedTile=3,selectedObject=1,drag=null,steelStart=null,shared=false,savedOwned=false;
const message=(s,error=false)=>{$('editorStatus').textContent=s;$('editorStatus').style.color=error?'#ad2929':'#315b37';};
const makeBlank=()=>({id:'custom-draft',rating:'Custom',number:0,name:'Mijn eerste level',total:10,required:8,timeSeconds:180,releaseRate:50,skills:[1,1,1,1,4,1,1,1],camera:0,style:0,specialStyle:0,special:false,width:960,height:160,terrain:Array.from({length:12},(_,i)=>({id:3,x:i*80,y:136,flip:false,behind:false,erase:false})),steel:[],objects:[{id:1,x:20,y:110,flip:false,noOverwrite:true,onTerrain:false},{id:0,x:870,y:119,flip:false,noOverwrite:true,onTerrain:false}]});
const snap=n=>Math.round(n/(Number($('gridSize').value)||1))*(Number($('gridSize').value)||1);
function bindFields(){
  $('levelName').value=data.name;$('levelWidth').value=String(data.width);$('levelStyle').value=String(data.style);
  $('levelTotal').value=data.total;$('levelRequired').value=data.required;$('levelTime').value=data.timeSeconds;$('levelRate').value=data.releaseRate;
  document.querySelectorAll('[data-skill-index]').forEach(el=>el.value=data.skills[Number(el.dataset.skillIndex)]||0);
  canvas.width=data.width;canvas.height=data.height;$('canvasSize').textContent=`${data.width} × ${data.height}`;
}
function readFields(){
  data.steel=data.steel||[];
  data.name=$('levelName').value.trim()||'Naamloos level';data.width=Number($('levelWidth').value);data.height=160;data.style=Number($('levelStyle').value);
  data.total=Number($('levelTotal').value);data.required=Number($('levelRequired').value);data.timeSeconds=Number($('levelTime').value);data.releaseRate=Number($('levelRate').value);
  data.skills=[...document.querySelectorAll('[data-skill-index]')].map(el=>Math.max(0,Math.min(99,Number(el.value)||0)));
  data.terrain=data.terrain.filter(p=>p.x<data.width).map(p=>{const tile=assets.styles[data.style].terrain.find(t=>t.id===p.id);return {...p,x:Math.max(0,Math.min(data.width-(tile?.w||1),p.x)),y:Math.max(0,Math.min(data.height-(tile?.h||1),p.y))};});
  data.objects=data.objects.map(p=>{const frame=assets.object(data.style,p.id)?.frames[0];return {...p,x:Math.max(0,Math.min(data.width-(frame?.w||1),p.x)),y:Math.max(0,Math.min(data.height-(frame?.h||1),p.y))};});
  data.steel=data.steel.map(p=>({...p,w:Math.min(p.w,data.width-p.x),h:Math.min(p.h,data.height-p.y)})).filter(p=>p.w>0&&p.h>0);
  canvas.width=data.width;canvas.height=data.height;$('canvasSize').textContent=`${data.width} × ${data.height}`;
}
function buildControls(){
  const skills=$('skillFields');skills.replaceChildren();names.forEach((name,i)=>{const label=document.createElement('label');label.textContent=name;const input=document.createElement('input');input.type='number';input.min='0';input.max='99';input.dataset.skillIndex=i;label.append(input);skills.append(label);});
  const select=$('levelStyle');assets.styles.forEach(style=>{const o=document.createElement('option');o.value=style.id;o.textContent=style.name[0].toUpperCase()+style.name.slice(1);select.append(o);});
  for(const id of ['levelName','levelWidth','levelStyle','levelTotal','levelRequired','levelTime','levelRate'])$(id).addEventListener('input',()=>{readFields();draw();});
  $('skillFields').addEventListener('input',()=>readFields());
}
function selectTool(tool){selectedTool=tool;document.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===tool)));$('terrainPalette').hidden=tool!=='terrain';$('objectPalette').hidden=tool!=='object';}
function drawPalette(){
  const style=assets.styles[data.style],tiles=$('terrainPalette'),objects=$('objectPalette');tiles.replaceChildren();objects.replaceChildren();
  for(const tile of style.terrain){const b=document.createElement('button');b.type='button';b.className='palette-item';b.setAttribute('aria-pressed',String(tile.id===selectedTile));b.title=`Terrein ${tile.id} · ${tile.w} × ${tile.h}`;const c=document.createElement('canvas');c.width=tile.w;c.height=tile.h;c.getContext('2d').drawImage(style.image,tile.x,tile.y,tile.w,tile.h,0,0,tile.w,tile.h);b.append(c);b.addEventListener('click',()=>{selectedTile=tile.id;drawPalette();});tiles.append(b);}
  for(const obj of style.objects.filter(o=>o.kind!=='unknown-special')){const b=document.createElement('button');b.type='button';b.className='palette-item';b.setAttribute('aria-pressed',String(obj.id===selectedObject));b.title=`${obj.kind} ${obj.id}`;const f=obj.frames[0],c=document.createElement('canvas');c.width=f.w;c.height=f.h;assets.drawFrame(c.getContext('2d'),data.style,f,0,0);const label=document.createElement('span');label.textContent=`${obj.kind} · ${obj.id}`;b.append(c,label);b.addEventListener('click',()=>{selectedObject=obj.id;drawPalette();});objects.append(b);}
}
function draw(){
  if(!data||!assets.styles[data.style])return;readFields();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=assets.styles[data.style].background;ctx.fillRect(0,0,canvas.width,canvas.height);
  if(data.specialStyle){const bg=assets.specialBackgrounds[data.specialStyle-1];if(bg){ctx.save();ctx.globalAlpha=.28;for(let x=0;x<canvas.width;x+=bg.width)ctx.drawImage(bg,x,0);ctx.restore();}}
  let terrain;try{terrain=new Terrain(data,assets);terrain.drawObjects(ctx,0,false);ctx.drawImage(terrain.canvas,0,0);terrain.drawObjects(ctx,0,true);}catch(error){message(error.message,true);return;}
  ctx.save();ctx.strokeStyle='#ffffff66';ctx.lineWidth=1;ctx.setLineDash([3,3]);for(let x=0;x<canvas.width;x+=32){ctx.beginPath();ctx.moveTo(x+.5,0);ctx.lineTo(x+.5,canvas.height);ctx.stroke();}ctx.setLineDash([]);ctx.strokeStyle='#ffdc55';ctx.lineWidth=2;ctx.strokeRect(.5,.5,canvas.width-1,canvas.height-1);ctx.restore();
  if(steelStart){const p=pointAt(steelStart.event);const x=Math.min(steelStart.x,p.x),y=Math.min(steelStart.y,p.y),w=Math.abs(p.x-steelStart.x)||8,h=Math.abs(p.y-steelStart.y)||8;ctx.fillStyle='#dde6eb99';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#e9f5ff';ctx.strokeRect(x+.5,y+.5,w,h);}
}
function pointAt(event){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(data.width-1,Math.floor((event.clientX-r.left)*data.width/r.width))),y:Math.max(0,Math.min(data.height-1,Math.floor((event.clientY-r.top)*data.height/r.height)))}}
function boxOf(p,kind){if(kind==='terrain'){const t=assets.styles[data.style].terrain.find(x=>x.id===p.id);return{x:p.x,y:p.y,w:t?.w||1,h:t?.h||1}}if(kind==='object'){const o=assets.object(data.style,p.id),f=o?.frames[0];return{x:p.x,y:p.y,w:f?.w||1,h:f?.h||1}}return{x:p.x,y:p.y,w:p.w,h:p.h};}
function hit(x,y){for(let i=data.objects.length-1;i>=0;i--){const b=boxOf(data.objects[i],'object');if(x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h)return{kind:'object',i};}for(let i=data.steel.length-1;i>=0;i--){const b=boxOf(data.steel[i],'steel');if(x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h)return{kind:'steel',i};}for(let i=data.terrain.length-1;i>=0;i--){const b=boxOf(data.terrain[i],'terrain');if(x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h)return{kind:'terrain',i};}return null;}
function addAt(p){const x=snap(p.x),y=snap(p.y);if(selectedTool==='terrain')data.terrain.push({id:selectedTile,x,y,flip:false,behind:false,erase:false});else if(selectedTool==='object')data.objects.push({id:selectedObject,x,y,flip:false,noOverwrite:true,onTerrain:false});draw();}
canvas.addEventListener('pointerdown',e=>{if(e.button===2)return;const p=pointAt(e);canvas.setPointerCapture(e.pointerId);if(selectedTool==='steel'){steelStart={x:snap(p.x),y:snap(p.y),event:e};draw();return;}if(selectedTool==='erase'){const h=hit(p.x,p.y);if(h)data[h.kind==='terrain'?'terrain':h.kind==='object'?'objects':'steel'].splice(h.i,1);draw();return;}const h=hit(p.x,p.y);if(h&&h.kind===selectedTool){drag={...h,start:p,origin:{...data[h.kind==='terrain'?'terrain':h.kind==='object'?'objects':'steel'][h.i]}};}else addAt(p);});
canvas.addEventListener('pointermove',e=>{if(!drag&&!steelStart)return;const p=pointAt(e);if(steelStart){steelStart.event=e;draw();return;}const items=data[drag.kind==='terrain'?'terrain':drag.kind==='object'?'objects':'steel'],item=items[drag.i];if(item){item.x=Math.max(0,Math.min(data.width-1,drag.origin.x+snap(p.x-drag.start.x)));item.y=Math.max(0,Math.min(data.height-1,drag.origin.y+snap(p.y-drag.start.y)));draw();}});
canvas.addEventListener('pointerup',e=>{if(steelStart){const p=pointAt(e),x=Math.min(steelStart.x,snap(p.x)),y=Math.min(steelStart.y,snap(p.y));data.steel.push({x,y,w:Math.max(8,Math.abs(snap(p.x)-steelStart.x)),h:Math.max(8,Math.abs(snap(p.y)-steelStart.y))});steelStart=null;draw();}drag=null;});
canvas.addEventListener('pointercancel',()=>{drag=null;steelStart=null;draw();});
canvas.addEventListener('contextmenu',e=>{e.preventDefault();const p=pointAt(e),h=hit(p.x,p.y);if(h)data[h.kind==='terrain'?'terrain':h.kind==='object'?'objects':'steel'].splice(h.i,1);draw();});
function validate(d){if(!d||typeof d!=='object'||typeof d.name!=='string'||!d.name.trim()||d.name.length>64||![320,640,960,1280].includes(Number(d.width))||d.height!==160||!Number.isInteger(Number(d.style))||Number(d.style)<0||Number(d.style)>4||!Number.isInteger(d.total)||d.total<1||d.total>100||!Number.isInteger(d.required)||d.required<1||d.required>d.total||!Number.isInteger(d.timeSeconds)||d.timeSeconds<30||d.timeSeconds>3600||!Number.isInteger(d.releaseRate)||d.releaseRate<1||d.releaseRate>99||!Array.isArray(d.terrain)||!Array.isArray(d.objects)||!Array.isArray(d.skills)||d.skills.length!==8||!Array.isArray(d.steel||[]))throw Error('Dit levelbestand heeft geen geldige Lemming Rescue-levelstructuur.');for(const t of d.terrain)if(!assets.styles[d.style].terrain.some(x=>x.id===t.id)||!Number.isInteger(t.x)||!Number.isInteger(t.y))throw Error('Het bestand verwijst naar een onbekend terreindeel.');for(const o of d.objects)if(!assets.object(d.style,o.id)||!Number.isInteger(o.x)||!Number.isInteger(o.y))throw Error('Het bestand verwijst naar een onbekend object.');const kinds=d.objects.map(o=>assets.object(d.style,o.id)?.kind);if(!kinds.includes('entrance')||!kinds.includes('exit'))throw Error('Plaats minstens één ingang en één uitgang.');}
async function api(url,init={}){const r=await fetch(url,{...init,headers:{'content-type':'application/json',...(init.headers||{})}});const result=await r.json().catch(()=>({}));if(!r.ok)throw Error(result.error||`Serverfout (${r.status})`);return result;}
function applyData(next,isShared=null,isSaved=false){data=structuredClone(next);shared=Boolean(isShared);savedOwned=Boolean(isSaved&&!shared);bindFields();drawPalette();draw();$('shareLevel').disabled=!savedOwned;$('deleteLevel').disabled=!savedOwned;message(shared?`Gedeeld door ${isShared.owner||'een gebruiker'}; sla op om je eigen kopie te maken.`:'Klaar. Sla je wijzigingen op om ze op je account te bewaren.');}
async function refreshList(keepId=''){const r=await api('/api/levels');records=r.levels;$('savedLevels').replaceChildren(new Option('Nieuw level',''));for(const item of records){const o=new Option(`${item.data.name}${item.shared?` · gedeeld door ${item.owner}`:''}`,item.id);$('savedLevels').append(o);}if(keepId)$('savedLevels').value=keepId;}
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>selectTool(b.dataset.tool)));
$('newLevel').addEventListener('click',()=>applyData(makeBlank()));$('loadLevel').addEventListener('click',()=>{const item=records.find(r=>r.id===$('savedLevels').value);if(item)applyData(item.data,item.shared?item:null,!item.shared);});
$('saveLevel').addEventListener('click',async()=>{try{readFields();validate(data);const editing=savedOwned;const result=await api(editing?`/api/levels/${encodeURIComponent(data.id)}`:'/api/levels',{method:editing?'PUT':'POST',body:JSON.stringify({data})});if(result.id)data.id=result.id;shared=false;savedOwned=true;await refreshList(data.id);$('shareLevel').disabled=false;$('deleteLevel').disabled=false;sessionStorage.removeItem('lr-editor-draft');message('Level opgeslagen bij jouw account.');}catch(e){message(e.message,true);}});
$('deleteLevel').addEventListener('click',async()=>{if(!savedOwned||!confirm(`Verwijder '${data.name}' en trek gedeelde toegang in?`))return;try{await api(`/api/levels/${encodeURIComponent(data.id)}`,{method:'DELETE'});await refreshList();applyData(makeBlank());message('Level en gedeelde toegang verwijderd.');}catch(e){message(e.message,true);}});
$('shareLevel').addEventListener('click',async()=>{try{if(!savedOwned)throw Error('Sla het level eerst op.');const username=$('shareUsername').value.trim();if(!username)throw Error('Vul de gebruikersnaam van de ontvanger in.');const result=await api(`/api/levels/${encodeURIComponent(data.id)}/share`,{method:'POST',body:JSON.stringify({username})});$('shareStatus').textContent=`Privé gedeeld met ${result.username}.`;message('Alleen deze gebruiker kan het level nu openen.');}catch(e){$('shareStatus').textContent=e.message;}});
$('revokeShare').addEventListener('click',async()=>{try{if(!savedOwned)throw Error('Sla het level eerst op.');const username=$('shareUsername').value.trim();if(!username)throw Error('Vul de gebruikersnaam in waarvoor je delen wilt intrekken.');await api(`/api/levels/${encodeURIComponent(data.id)}/share`,{method:'DELETE',body:JSON.stringify({username})});$('shareStatus').textContent=`Delen met ${username} ingetrokken.`;}catch(e){$('shareStatus').textContent=e.message;}});
$('playtest').addEventListener('click',()=>{try{readFields();validate(data);const testData=structuredClone(data);testData.id='custom-playtest';testData.rating='Custom';testData.number=0;testData.camera=0;sessionStorage.setItem('lr-editor-draft',JSON.stringify({data,savedOwned}));sessionStorage.setItem('lr-editor-playtest',JSON.stringify(testData));location.href='/';}catch(e){message(e.message,true);}});
$('exportLevel').addEventListener('click',()=>{readFields();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`lemming-rescue-${(data.name||'level').toLowerCase().replace(/[^a-z0-9]+/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
$('importLevel').addEventListener('change',async e=>{const f=e.target.files?.[0];e.target.value='';try{if(!f)return;if(f.size>150000)throw Error('Levelbestanden mogen maximaal 150 kB zijn.');const next=JSON.parse(await f.text());validate(next);next.id='custom-import';applyData(next);message('Levelbestand geïmporteerd. Sla het op om het aan jouw account toe te voegen.');}catch(err){message(err.message,true);}});
async function boot(){try{await assets.ready;buildControls();let draft=null;try{draft=JSON.parse(sessionStorage.getItem('lr-editor-draft')||'null');}catch{sessionStorage.removeItem('lr-editor-draft');}if(draft?.data){validate(draft.data);applyData(draft.data,null,Boolean(draft.savedOwned));}else applyData(makeBlank());await refreshList(data.id);}catch(e){message(`Levelbouwer laden mislukt: ${e.message}`,true);}}
boot();
