import {ClassicAssets} from './classic-assets.js';
import {NativeSprites} from './native-sprites.js';
import {VersusEngine} from './versus-engine.js';
import {TICK,SKILLS} from './lemming-native.js';
const $=id=>document.getElementById(id),canvas=$('field'),ctx=canvas.getContext('2d',{alpha:false});
const labels=['Klimmer','Zwever','Bomber','Blokkeren','Bouwer','Basher','Mijnwerker','Graver'];
const anim=['klimmen','parachute','ohno','blokkeren','bouwen','bashen','mijnen','graven'];
const assets=new ClassicAssets(),sprites=new NativeSprites();let levels=[],engine=null,index=0,team=0,skill=-1,paused=true,started=false,zoom=1,cameraX=0,last=0,acc=0,selected=null,drag=null;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function setTeam(n){team=n;document.querySelectorAll('.turns button').forEach(b=>b.classList.toggle('active',Number(b.dataset.team)===team));renderSkills();}
function renderSkills(){const root=$('skills');root.replaceChildren();if(!engine)return;SKILLS.forEach((_,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-pressed',String(skill===i));b.disabled=engine.teamSkills[team][i]<=0||engine.finished;b.innerHTML=`<b>${engine.teamSkills[team][i]}</b><span>${labels[i]}</span>`;b.addEventListener('click',()=>{skill=skill===i?-1:i;renderSkills();$('state').textContent=skill<0?'Geen vaardigheid geselecteerd.':`${labels[i]} geselecteerd voor speler ${team+1}. Klik op een lemming.`;});root.append(b);});}
function reset(i=index){index=i;engine=new VersusEngine(levels[index],assets);engine.silent=true;team=0;skill=-1;cameraX=clamp(engine.data.camera||0,0,engine.data.width-320/zoom);paused=true;started=false;selected=null;$('level').value=String(index);$('title').textContent=engine.data.name;$('objective').textContent=`${engine.data.total} lemmings · ${engine.data.timeSeconds/60} minuten · ${engine.entrances.length} ingang${engine.entrances.length===1?'':'en'}`;$('intro').hidden=false;$('pause').textContent='Start';$('state').textContent='Kies welke speler je bedient.';renderSkills();updateScore();draw();}
function start(){if(!engine)return;started=true;paused=false;$('intro').hidden=true;$('pause').textContent='Pauze';$('state').textContent='Spel loopt. Kies een team om vaardigheden toe te wijzen.';last=0;}
function pause(){if(!started){start();return;}paused=!paused;$('pause').textContent=paused?'Verder':'Pauze';last=0;acc=0;}
function updateScore(){if(!engine)return;for(let n=0;n<2;n++){$(`score${n}`).querySelector('strong').textContent=engine.exitScores[n];$(`score${n}`).querySelector('small').textContent=`skills: ${engine.teamSkills[n].reduce((a,b)=>a+b,0)} · gered`;}if(engine.finished){paused=true;$('pause').textContent='Klaar';const [a,b]=engine.exitScores;$('state').textContent=a===b?`Gelijkspel: ${a}–${b}.`:`Speler ${a>b?1:2} wint met ${Math.max(a,b)}–${Math.min(a,b)}.`;}}
function draw(){if(!engine)return;const l=engine.level;l.flush();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle=l.style.background;ctx.fillRect(0,0,320,160);ctx.save();ctx.scale(zoom,zoom);ctx.translate(-Math.floor(cameraX),0);if(l.specialBackground){const bg=l.specialBackground;for(let x=Math.floor(cameraX/bg.width)*bg.width;x<cameraX+320/zoom;x+=bg.width)ctx.drawImage(bg,x,0);}l.drawObjects(ctx,engine.tick,false);ctx.drawImage(l.canvas,0,0);l.drawObjects(ctx,engine.tick,true);for(const e of engine.entities){sprites.draw(ctx,e,engine.tick,assets,e.id===selected);if(e.alive){ctx.fillStyle=e.team===0?'#38ef66':'#53baff';ctx.fillRect(Math.round(e.x)-1,Math.round(e.y)-15,3,2);}}ctx.restore();}
function tick(){if(!started||paused||engine.finished)return;engine.step();if(engine.tick%5===0){draw();updateScore();renderSkills();}}
function frame(now){requestAnimationFrame(frame);if(!engine)return;if(!last)last=now;const dt=Math.min(.2,(now-last)/1000);last=now;if(!paused&&started){acc+=dt;let steps=0;while(acc>=TICK&&steps++<10){tick();acc-=TICK;}}draw();}
function eventPoint(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*320,y:(e.clientY-r.top)/r.height*160};}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,cam:cameraX,moved:false,point:eventPoint(e)};});
canvas.addEventListener('pointermove',e=>{if(!drag)return;if(Math.abs(e.clientX-drag.x)>5){drag.moved=true;cameraX=clamp(drag.cam-(e.clientX-drag.x)/canvas.getBoundingClientRect().width*320/zoom,0,engine.data.width-320/zoom);draw();}});
canvas.addEventListener('pointerup',e=>{if(!drag)return;if(!drag.moved){const p=eventPoint(e),wx=p.x/zoom+cameraX,wy=p.y/zoom;const candidates=engine.live.filter(l=>Math.abs(l.x-wx)<=7&&Math.abs(l.y-wy)<=10).sort((a,b)=>Math.abs(a.x-wx)+Math.abs(a.y-wy)-Math.abs(b.x-wx)-Math.abs(b.y-wy));const hit=candidates[0];if(hit){if(skill>=0&&hit.team===team){const chosen=skill;if(engine.command({type:'skill',skill:chosen,lemming:hit.id,team})){skill=-1;$('state').textContent=`${labels[chosen]} toegepast.`;}else $('state').textContent='Deze vaardigheid kan hier niet worden toegepast.';}else{$('state').textContent=`Lemming van speler ${hit.team+1} geselecteerd.`;}selected=hit.id;renderSkills();draw();}}drag=null;});
document.querySelectorAll('.turns button').forEach(b=>b.addEventListener('click',()=>setTeam(Number(b.dataset.team))));
$('level').addEventListener('change',e=>reset(Number(e.target.value)));$('start').addEventListener('click',start);$('pause').addEventListener('click',pause);$('restart').addEventListener('click',()=>reset(index));$('zoom').addEventListener('click',()=>{zoom=zoom%3+1;cameraX=clamp(cameraX,0,engine.data.width-320/zoom);$('zoom').textContent=`Zoom ${zoom}×`;draw();});
document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){cameraX=clamp(cameraX-20,0,engine.data.width-320/zoom);draw();}else if(e.key==='ArrowRight'){cameraX=clamp(cameraX+20,0,engine.data.width-320/zoom);draw();}else if(e.key===' '){e.preventDefault();pause();}});
async function boot(){try{await Promise.all([assets.ready,sprites.nativeReady]);const r=await fetch('/assets/classic/two-player-levels.json');if(!r.ok)throw Error('De tweespelerslevels konden niet worden geladen.');levels=await r.json();$('level').replaceChildren(...levels.map((l,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=`${String(i+1).padStart(2,'0')} · ${l.name}`;return o;}));reset(0);requestAnimationFrame(frame);}catch(e){$('state').textContent=e.message;}}
boot();
